name: bezier_simple_connect_viewer
description: Data visualization web application

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: "^5.0.0-beta"
  angular_components: "^0.9.0-beta"
  sass_builder: ^2.1.0
  vector_math: ^2.0.7
  json_annotation: "^0.2.9"
  js: "^0.6.1"
  logging: "^0.11.3+1"
  test:
  color_picker: "^1.1.4"
  spreadsheet_decoder: "^1.0.0"
  platform_detect: "^1.3.3"
  chronosgl: "^3.3.0"
  observable: "^0.22.1+3"
  async: "^2.0.7"

dev_dependencies:
  build_runner: "^0.9.1"
  build_web_compilers: "^0.4.0+4"

web:
  compiler:
    debug: dartdevc
